### ISSUE TITLE
API der CLI bietet kein Write ohne Zeilenumbruch an

### ISSUE THREAD

**Issue by whoTBecker** [DanielJerolm/gpcc#4]
Das CLI sieht aktuell vor, dass jede Ausgabe in eine neue Zeile kommt.
Ausgaben ohne Zeilenumbruch werden nicht unterstützt.

**Comment by DanielJerolm** [comment]
I assume the use case for this feature is displaying a progress indicator like a growing percentage number or a rotating "/" character. Currently the CLI only offers CLI::WriteLine() (and some variants) which print any text output on a new line.

There is good reason to do so:
In addition to CLI commands, other software components may use the CLI to print text to the terminal such as an gpcc::log::Backend_CLI instance printing log messages. If the CLI would allow to "rewrite" the previous line, then the output emitted by other software components could be overwritten or corrupted. This is not desired.

However, I have a idea how overwriting the output of other software components could be avoided:
First, I assume that overwriting the last line makes only sense for output printed by a CLI command. I think it makes no sense for log messages and no sense for output generated by any other software component except CLI command handler functions.

Based on that assumption, the requested feature could be implemented as follows:
The CLI could offer a CLI::RewritePrevLine() method in addition to the existing CLI::WriteLine(). The CLI can easily determine via gpcc::osal::Thread::IsItMe() if those methods were called by a CLI command handler (CLI thread) or a different software component (non-CLI thread). CLI::RewritePrevLine() could be implemented in a way that it only overwrites lines that have been printed by a CLI command handler. If the previous line was printed by a different software component (e.g. log system), or by a different CLI command handler function, CLI::RewritePrevLine() would behave like CLI::WriteLine().

What do you think?
There are further some options that need discussion:
- Invoking CLI::RewritePrevLine() by something else but a CLI command handler could be treated as a logic error.
- Passing text containing '\n' to CLI::RewritePrevLine() may generate strange results on the terminal's screen. Accept this or check and treat as error?

**Comment by whoTBecker** [comment]
This seems to be a valid solution.

For the last described scenario "Passing text containing '\n' to CLI::RewritePrevLine()", there could be an use case where several previous lines should be rewritten. In that case, CLI::RewritePrevLine() may take an argument for the desired number of lines to go back in terminal.
So, the user has the possibility to rewrite several lines, but also should be responsible to prevent strange results on the terminal's screen by himself.

**Comment by DanielJerolm** [comment]
Thanks for your input. Some thoughts of mine:
- @whoTBecker, I think rewriting multiple lines is not KISS. I also do not see any real use case for that.
- In general I would appreciate if the user does not pass any control characters to WriteLine() at all, except for "\n". Reason: The input prompt at the bottom must always be preserved, incl. potential user input. And that is best done by CLI.
- @Andreas143 I like your idea. I think CLI would just have to track if there was a WriteLine() before a Rewrite() and adapt the behavior of Rewrite() accordingly.
- There must be no more than one component using Rewrite() to avoid rewriting the output of someone else. I think the only reasonable user is a CLI command handler. Should that constraint be enforced?

**Comment by DanielJerolm** [comment]
How to distinguish different components?

**Comment by Wishmaster-de** [comment]
Good new feature. I think a lot users will like it. :thumbsup:
